title: Sener BimTools Docs
description: Official documentation for the Sener BimTools Revit plugin.
theme: just-the-docs

# Path to the favicon
favicon_ico: "/assets/images/favicon.png"
logo: "/assets/images/logo.png"

aux_links:
  "Downloads":
    - "https://github.com/SnrBim/BimTools/releases"
  "ðŸŒ™":
    - "toggleTheme"

exclude:
  - .history

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "ru", "es"]

exclude_from_localizations: ["assets"]

