title: Sener BimTools Docs
description: Official documentation for the Sener BimTools Revit plugin.
theme: just-the-docs

url: "https://snrbim.github.io"
baseurl: ""

# Path to the favicon
favicon_ico: "/assets/images/favicon.png"
logo: "/assets/images/logo.png"

aux_links:
  "Downloads":
    - "https://github.com/SnrBim/BimTools/releases"
  "ðŸŒ™":
    - "toggleTheme"
  "EN":
    - "langEn"
  "ES":
    - "langEs"

exclude:
  - .history
  - vendor

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "es"]

exclude_from_localizations: ["assets"]

back_to_top: true
back_to_top_text: "Back to top"

aux_links_new_tab: true
