title: BimTools Docs
description: Official documentation for the Sener BimTools Revit plugin.
theme: just-the-docs

# Path to the favicon
favicon_ico: "/assets/images/favicon.svg"

aux_links:
  "Downloads":
    - "https://github.com/SnrBim/BimTools/releases"
  "ðŸŒ™":
    - "toggleTheme"

exclude:
  - .history
